# configuration for future smart thermostat

# configuration for cooling
- platform: generic_thermostat 
  name: Main Cooling
  heater: switch.main_cooling
  target_sensor: sensor.main_temperature
  ac_mode: True
  min_temp: 68
  max_temp: 85
  target_temp: 78
  cold_tolerance: 1
  hot_tolerance: 1
  initial_operation_mode: auto
  away_temp: 82
################################################################################
# configuration for heating
- platform: generic_thermostat
  name: Main Heating
  heater: switch.main_heating
  target_sensor: sensor.main_temperature
  ac_mode: False
  min_temp: 60
  max_temp: 75
  target_temp: 68
  cold_tolerance: 1
  hot_tolerance: 1
  initial_operation_mode: auto
  away_temp: 64

