- platform: generic_thermostat
  name: Office
  heater: switch.upstairs_fan
  min_temp: 70
  max_temp: 85
  target_temp: 78
  min_cycle_duration:
    minutes: 10
  ac_mode: true
  target_sensor: sensor.office_temperature
  cold_tolerance: 0.5
  hot_tolerance: 0.5
  initial_hvac_mode: "off"
  away_temp: 80
  precision: 0.1
