- platform: kodi
  host: !secret kodi_office_ip
  name: Kodi Office
- platform: kodi
  host: !secret media_ip
  name: Kodi Media
- platform: plex
  name: Plex
  ip_address: !secret media_ip
  entity_namespace: plex
  show_all_controls: True

- platform: roku
  host: !secret roku_master
  name: Roku Master

- platform: roku
  name: Roku Office
  host: !secret roku_office

- platform: roku
  name: Roku Living
  host: !secret roku_living

