################################################################################
# log file notification
################################################################################

- name: logfile
  platform: file
  filename: /var/tmp/ha_notify.log

################################################################################
# twitter notification
################################################################################

- name: twitter
  platform: twitter
  consumer_key: !secret twitter_consumer_key
  consumer_secret: !secret twitter_consumer_secret
  access_token: !secret twitter_access_token
  access_token_secret: !secret twitter_access_secret

################################################################################
# kodi notification
################################################################################

- platform: kodi
  name: kodi_media
  host: !secret media_ip

- platform: kodi
  name: kodi_office
  host: !secret office_ip

